Enh ext ahmed body loss
NVIDIA/modulus-launch pull request #101
Opened 2023-08-22 23:47 UTC by mnabian

# Modulus Pull Request

## Description

Closes https://github.com/NVIDIA/modulus-launch/issues/82

## Checklist

- [ ] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [ ] New or existing tests cover these changes.
- [ ] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is
up to date with these changes.

## Dependencies

2023-08-22 23:47 UTC, mnabian commented
/blossom-ci

2023-08-28 21:35 UTC, mnabian commented
/blossom-ci

2023-09-18 22:16 UTC, mnabian commented
/blossom-ci

2023-09-22 22:48 UTC, mnabian commented
/blossom-ci

2023-09-22 22:51 UTC, NickGeneva requested changes

2023-09-22 22:51 UTC, NickGeneva commented on examples/cfd/ahmed_body_mgn/train.py
> +info("Training completed!")
logger.info

2023-09-22 22:51 UTC, NickGeneva approved these changes

2023-09-22 23:30 UTC, mnabian commented
/blossom-ci

2023-09-22 23:40 UTC, mnabian commented on examples/cfd/ahmed_body_mgn/train.py
> +info("Training completed!")
Fixed

2023-09-22 23:40 UTC, merged