ERA5 Mirror
NVIDIA/modulus-launch pull request #104
Opened 2023-09-08 17:42 UTC by loliverhennigh

# Modulus Pull Request

related to issue https://github.com/NVIDIA/modulus-launch/issues/103

## Description
Download support from CDS api for training weather models. This allows any user to get the needed data to train ForcastNet for example.

closes issue https://github.com/NVIDIA/modulus-launch/issues/103

## Checklist

- [*] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [*] New or existing tests cover these changes.
- [*] The documentation is up to date with these changes.
- [*] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is
up to date with these changes.

2023-09-08 21:05 UTC, loliverhennigh commented
/blossom-ci

2023-09-08 21:27 UTC, loliverhennigh commented
/blossom-ci

2023-09-11 16:33 UTC, dallasfoster requested changes

2023-09-11 16:33 UTC, dallasfoster commented on examples/weather/dataset_download/README.md
> +This repository provides tools for downloading ERA5 datasets via the CDS API and processing them into formats suitable for machine learning. Users can flexibly select different meteorological variabl
".. via the Climate Data Store (CDS) API ..."

2023-09-11 16:33 UTC, dallasfoster commented on examples/weather/dataset_download/README.md
> +2. Run the main script, `python start_mirror.py`. This will perform all actions needed to generate HDF5 files needed for training. First it will download and save all variables as Zarr arrays. This m
Is there more documentation somewhere about the "restart without issue" line? Why are we saving as HDF5? Is this just for internal benefit? I don't know why we need to provide a public utility that converts from the zarr stores to HDF5.

2023-09-11 16:33 UTC, dallasfoster commented on examples/weather/dataset_download/README.md
> +- `start_train_year`: Start year for training data.
Can we replace `start_train_year` and `end_train_year` with something more flexible like `start_train_date` and `end_train_date`?

2023-09-11 16:33 UTC, dallasfoster commented on examples/weather/dataset_download/README.md
> +- `start_train_year`: Start year for training data.
I also don't know if I think this utility should separate out train/test/out_of_sample. Shouldn't that be another task for the user?

I have had applications where my train dates were September 2018-March 2020 but the last three months I sub-selected every other week and test dates were March 2020-December 2020. My point is that in weather and climate data does not always naturally get segregated into years and it might be over-engineering to provide these details in this utility.

2023-09-11 16:33 UTC, dallasfoster commented on examples/weather/dataset_download/README.md
> +- `compute_mean_std`: Whether or not to compute global mean and standard deviation.
Again, I do not think that this function needs to be in this utility. This utility should be a stand-alone mirror. I think we should design a more modular set of utilities instead of trying to design a single monolithic data preprocessing utility.

Consider the following separate utilities:
Data mirroring
HDF5 conversion
Train/Test Splitting
Computing of Statistics

Each of these should be separate utilities with their own sets of options and customizations.

2023-09-11 16:33 UTC, dallasfoster commented on examples/weather/dataset_download/era5_mirror.py
> +        if not os.path.exists(self.base_path):
Should we be using fsspec?

2023-09-11 16:33 UTC, dallasfoster commented on examples/weather/dataset_download/era5_mirror.py
> +        self.metadata_file = f"{self.base_path}/metadata.json"
Prefer `os.path.join(...)`

2023-09-11 16:33 UTC, dallasfoster commented on examples/weather/dataset_download/start_mirror.py
> +        print(f"Finished saving global mean and std at {stats_path}")
I think the reason I don't love this being a part of this utility is that there is no real benefit for it being here. It is not any more optimal to have the mean/var calculated as part of this utility and it is very rigid in how it defines `mean` and `std`.

2023-09-22 04:53 UTC, loliverhennigh commented on examples/weather/dataset_download/README.md
> +This repository provides tools for downloading ERA5 datasets via the CDS API and processing them into formats suitable for machine learning. Users can flexibly select different meteorological variabl
fixed

2023-09-22 05:07 UTC, loliverhennigh commented on examples/weather/dataset_download/README.md
> +2. Run the main script, `python start_mirror.py`. This will perform all actions needed to generate HDF5 files needed for training. First it will download and save all variables as Zarr arrays. This m
Added some explanation about the restart. Should work as long as the time configs don't change. Might make it more robust later though.

For saving as HDF5. Currently all our datapipes are set up to work on hdf5 files with a very specific file structure. This is not ideal but if we give this script to generate them at least people can start training models. Longer term I would like to completely remove the HDF5 files and use the Zarr datapipe we are building. There are some complication with this that we are still working out but when we get this done all HDF5 stuff can go away. That's my plan at least :).

2023-09-22 05:12 UTC, loliverhennigh commented on examples/weather/dataset_download/README.md
> +- `start_train_year`: Start year for training data.
For right now I would like to keep the year ranges as they are how we have the hdf5 files set up currently. Similarly with the `train` `test` `out_of_sample`. Right now I think this script should just be viewed as a fetcher for the data needed to train in our other recipes.

Like I mentioned in the above thread we will ideally move to zarr soon making all of this a lot easier. When we make this transition I will put a bit more work into this ERA5 mirror. I would like it to become more of a managed dataset builder that can fetch any variables and data ranges needed. Some of this is in the implementation now but its not all there yet.

2023-09-22 05:38 UTC, loliverhennigh commented
/blossom-ci

2023-09-22 16:33 UTC, NickGeneva commented on examples/weather/dataset_download/era5_mirror.py
> +        with tempfile.TemporaryDirectory() as tmpdir:
Can we use the modulus cache location for this temp dir?

2023-09-22 16:33 UTC, NickGeneva commented on examples/weather/dataset_download/era5_mirror.py
> +        zarr_path = self.variable_to_zarr_name(variable, pressure_level)
Is this a Fsspec mapping or a sting?

2023-09-22 16:33 UTC, NickGeneva commented on examples/weather/dataset_download/era5_mirror.py
> +                    if not self.chunk_exists(
Just wondering why you dont need to specify the day here

2023-09-22 16:33 UTC, NickGeneva commented on examples/weather/dataset_download/start_mirror.py
> +        print(f"Finished saving global mean and std at {stats_path}")
Typically mean and std are served with the model itself. Now with the use of the model registry this should become standard. I can see Dallas' point here.

2023-09-22 16:33 UTC, NickGeneva commented on examples/weather/dataset_download/start_mirror.py
> +        # HDF5 filename
Should be promoting the conversion of H5 over zarr?

Perhaps this should be a separate util one has to call in addition the the mirror?

2023-09-22 16:34 UTC, NickGeneva commented on examples/weather/dataset_download/conf/config_34var.yaml
> +  - "10m_u_component_of_wind"
Just to confirm, these are the name given by the CDS api?

2023-09-22 16:38 UTC, loliverhennigh commented on examples/weather/dataset_download/conf/config_34var.yaml
> +  - "10m_u_component_of_wind"
Yes

2023-09-22 16:40 UTC, loliverhennigh commented on examples/weather/dataset_download/start_mirror.py
> +        print(f"Finished saving global mean and std at {stats_path}")
If people want to train our models from scratch they will need these values though. Honestly I really don't like that we are keeping them this way at all but if we keep this it will make it consistent with our current datapipes.

2023-09-22 16:45 UTC, loliverhennigh commented on examples/weather/dataset_download/era5_mirror.py
> +                    if not self.chunk_exists(
I set this up to always download entire months. I think this is a good idea because the download speeds will crash if you try to make them too small.

2023-09-22 18:47 UTC, loliverhennigh commented
/blossom-ci

2023-09-22 19:03 UTC, loliverhennigh commented
Hey @dallasfoster and @NickGeneva . Pushed the fsspec change. I can give a filesystem for our object storage and upload/download the zarr arrays. There is a detail about how the permissions are set up on our storage but this should work for average users. I think this is ready for merging unless there is anything else.

2023-09-22 19:03 UTC, loliverhennigh commented
/blossom-ci

2023-09-22 21:01 UTC, NickGeneva approved these changes

2023-09-25 20:57 UTC, dallasfoster approved these changes

2023-09-25 20:58 UTC, loliverhennigh commented
/blossom-ci

2023-09-25 21:39 UTC, merged