Docs dlwp rnn
NVIDIA/modulus-launch pull request #80
Opened 2023-08-04 17:49 UTC by ktangsali

# Modulus Pull Request

## Description
Closes #70 

## Checklist

- [x] I am familiar with the [Contributing Guidelines](https://github.com/NVIDIA/modulus/blob/main/CONTRIBUTING.md).
- [x] New or existing tests cover these changes.
- [x] The documentation is up to date with these changes.
- [ ] The [CHANGELOG.md](https://github.com/NVIDIA/modulus/blob/main/CHANGELOG.md) is
up to date with these changes.

## Dependencies

2023-08-04 18:40 UTC, mnabian commented on examples/weather/dlwp/README.md
> +[Paper 1](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2021MS002502)
I suggest we put the name of the papers instead of just "paper 1" or "paper 2"

2023-08-07 16:54 UTC, ktangsali commented on examples/weather/dlwp/README.md
> +[Paper 1](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2021MS002502)
Done, thanks!

2023-08-07 18:18 UTC, ram-cherukuri approved these changes

2023-08-07 18:18 UTC, ram-cherukuri commented on examples/weather/dlwp/README.md
> +it are provided in the `data_curation` directory. A larger subset of dataset is hosted
Just confirming that additional pre-processing in not needed and the data is already in a format that can be fed into the training script.

2023-08-07 19:14 UTC, ktangsali commented on examples/weather/dlwp/README.md
> +it are provided in the `data_curation` directory. A larger subset of dataset is hosted
Currently pre-processing of the data is needed before being fed into the model. On-the-fly preprocessing is in the works, and can potentially be included in upcoming releases

2023-08-07 19:15 UTC, merged

2023-08-07 22:19 UTC, mnabian requested changes

2023-08-07 22:19 UTC, mnabian commented on examples/cfd/gray_scott_rnn/README.md
> +This example relies on the Dataset used in [Transformers for modeling physical systems](https://www.sciencedirect.com/science/article/abs/pii/S0893608021004500)
Do we want to provide instructions on how to download the dataset?

2023-08-07 22:19 UTC, mnabian commented on examples/cfd/gray_scott_rnn/README.md
> +In physics-ML, these models are critical in predicting dynamic physical systems’ evolution,
Maybe we should not say these models are "critical"

2023-08-07 22:19 UTC, mnabian commented on examples/cfd/navier_stokes_rnn/README.md
> +In physics-ML, these models are critical in predicting dynamic physical systems’ evolution,
Same here

2023-08-07 22:19 UTC, mnabian commented on examples/cfd/navier_stokes_rnn/README.md
> +The example uses 1000 training samples and 10 test samples.
No validation samples?

2023-08-07 22:19 UTC, mnabian commented on examples/cfd/navier_stokes_rnn/README.md
> +(many-to-many/seq-to-seq).
It'd be good to explain the pros/cons of these two approaches briefly.

2023-08-07 22:19 UTC, mnabian commented on examples/cfd/navier_stokes_rnn/README.md
> +python navier_stokes_rnn.py model_type=seq2seq
Not related to this PR, but we should use hydra configs instead of the argparse.

2023-08-07 22:19 UTC, mnabian commented on examples/weather/dlwp/README.md
> +near real-time digital twins for weather prediction
I wouldn't talk about digital twins here since that involves many more components...

2023-08-07 22:19 UTC, mnabian commented on examples/weather/dlwp/README.md
> +its future state u(t+Δt) by learning from historical observations of the weather,
Can we use LaTex equations here?